### ISSUE TITLE
wkhtmltopdf 0.12.1 compatibility?

### ISSUE THREAD

**Issue by agger-magenta** [zestsoftware/collective.sendaspdf#17]
I'm trying to run collective.sendaspdf on a server with wkhtmltopdf 0.12.1 installed.

This fails because of the option "--toc-header-text", whose syntax has apparently changed. The exact same setup works fine on another server with wkhtmltopdf 0.9.9

I'm able to get it to work by simply dropping 'toc-header-text' from the variable 'valued_options' in transforms/wk.py.  However, this doesn't seem very elegant and given this error string:

    Please check that you use a version compatible with your OS and the version is 0.9.

should collective.sendaspdf be considered "locked" to wkhtml 0.9.*? Are there plans to support later versions like 0.12+ at some point?

**Comment by mauritsvanrees** [comment]
The master branch now works with wkhtmltopdf 0.12.
