### ISSUE TITLE
Problem loading styles from https

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/collective.sendaspdf#19]
This has worked fine for a long time as far as I know. But today downloading an https page as pdf misses all styles. Somehow the styles (plus presumably any images) cannot be loaded.

It may be due to this stackoverflow question: http://stackoverflow.com/questions/26529863/how-do-i-configure-wkhtmltopdf-to-request-https-pages-by-url-not-ip-on-windows-8

Possibly a recent openssl update on the server causes this, but that is a guess.

It does not matter whether wkhtmltopdf itself is running on the server that hosts the https website, or locally on my laptop.  This gets executed:

  parts/wkhtmltopdf/wkhtmltopdf --disable-javascript --toc-header-text Inhoudsopgave --margin-right 10 --margin-left 10 --margin-bottom 10 --margin-top 10 --print-media-type file:///tempfile.html /tmp/tempfile.pdf

Any https links in tempfile.html cannot be loaded. When I replace https with http, it works just fine:

  cat tempfile.html | sed "s/https/http/g" > newfile.html

I tried just now with running wkhtmltopdf on https://google.com, but that looks fine. So there may be something wrongly configured on the server.

Workaround that I did on the server to fix it: I edited transforms/wk.py and in the html_to_pdf function I added a line `source = source.replace('https://', 'http://')`. (Yes, I did that by editing the collective.sendaspdf distribution on the server. I am bad.)

**Comment by maurits** [comment]
Omg



Groet,
Maurits

**Comment by mauritsvanrees** [comment]
@maurits: looks like you are still getting these message and are still annoyed by it. But you are still the only one who can stop that. You are watching the collective.sendaspdf repository. If you are not interested, just stop watching. Simply visit this page and click 'Not Watching': https://github.com/zestsoftware/collective.sendaspdf/subscription
